### PR TITLE
I think now 

### PR DESCRIPTION
**Pull request by superzackx**
I'm sorry about opening so many PRs but now it should work.

### CODE REVIEW

**Comment by DragonZV** [comment]
doesn't express require a views directory?

**Comment by superzackx** [comment]
I did that also try replying from a different repp with index.js in root.

**Comment by DragonZV** [comment]
just to confirm, did you use app.use? since another index.js is in root, app.use will be neccesary, as express assumes the views directory to be in root.

**Comment by DragonZV** [comment]
@superzackx Do you still want to merge the pr?

**Comment by superzackx** [comment]
Yes its gonna add a views dir which will probably make the website run.

**Comment by DragonZV** [comment]
@superzackx yes, but express by default will attempt to look for the views dir in root. What we have is a views dir in a website. To fix this, you need to use `<ExpressApp>.use`.

**Comment by DragonZV** [comment]
Wait no, app.set

**Comment by DragonZV** [comment]
Thank you for the contribution, @superzackx.

**Pull request merged**
