### PR TITLE
Fixed Website

### PR DESCRIPTION
**Pull request by superzackx**
Hello,

I have fixed a lil bit of your website code! It should work now.

### CODE REVIEW

**Comment by DragonZV** [comment]
we don't use process.env, due to to the fact that we have a json object for topgg, and website.
envs return a string, which means no json object can be used.
in https://github.com/HurricanoBot/Hurricano/blob/main/bot/utilities/config.js, we take care of that via JSON.parse, and the exports of that file is a property of client.

**Comment by DragonZV** [comment]
Thank you for your contribution, superzackx.

**Comment by superzackx** [comment]
Hi, you can always use manual port and IP in place of process.env.

**Comment by DragonZV** [comment]
yes, but this is meant to be open source and selfhostable, so I'd rather not

**Comment by DragonZV** [comment]
and my fix works anyway

**Pull request merged**
