### PR TITLE
Better Eval Command .-.

### PR DESCRIPTION
**Pull request by jeydinpham**
Look it's a better eval command that creates a Sourcebin link when the output gets too long. This is useful if you wanna...fetch all the guilds or something I don't know...

### CODE REVIEW

**Comment by DragonZV** [comment]
@Jeydin21 Thanks for the contribution!

**Comment by jeydinpham** [comment]
:o

**Comment by DragonZV** [comment]
@Jeydin21 Eval command kinda sucks, if the code that executes has an error, it projects the error into console and doesn't send the eval embed.

Code:
```js
const Discord = require ("discord.js");
const sourcebin = require('sourcebin_js')

module.exports = {
    name: "eval",
    description: "Evaluates arbituary JavaScript.",
    ownerOnly: true,
    args: true,
    run: async (message, args) => {

  const clean = text => {
  if (typeof(text) === "string")
    return text.replace(/`/g, "`" + String.fromCharCode(8203)).replace(/@/g, "@" + String.fromCharCode(8203));
  else
      return text;
}
        const code = args.join(" ");
      let evaled = eval(code);

      if (typeof evaled !== "string")
        evaled = require("util").inspect(evaled);


        if (clean(evaled).length > 1024 || code.length > 1024) {
          sourcebin.create([{
            name: `Code by ${message.author.tag}`,
            content: clean(evaled),
            languageId: 'js'
          }]).then(src => {
         var embed = new Discord.MessageEmbed()
         .setTitle("Evaled:")
         .setColor("#ffb6c1")
         .addField("Evaled: :inbox_tray:",  `\`\`\`js\n${code}\n\`\`\``)
         .addField("Output: :outbox_tray:", `Output is to large! [Click here.](${src.url})`)
         message.channel.send({ embed: embed })
          }).catch(e => {
            message.channel.send(`Error: ${e}`)
      });
} else {
        var embed2 = new Discord.MessageEmbed()
        .setTitle("Evaled:")
        .setColor("#ffb6c1")
        .addField("Evaled: :inbox_tray:",  `\`\`\`js\n${code}\n\`\`\``)
        .addField("Output: :outbox_tray:", `\`\`\`js\n${clean(evaled)}\n\`\`\``)
        message.channel.send({embed : embed2 });
}
    }, catch (err) {
        const code = args.join(" ");
                if (clean(err).length > 1024 || code.length > 1024) {
                  sourcebin.create([{
                    name: `Code by ${message.author.tag}`,
                    content: clean(err),
                    languageId: 'js'
                  }]).then(src => {
                 var embed = new Discord.MessageEmbed()
                 .setTitle("Evaluation Overload!")
                 .setColor("#ffb6c1")
                 .addField("Evaled: :inbox_tray:",  `\`\`\`js\n${code}\n\`\`\``)
                 .addField("Output: :outbox_tray:", `Output is to large! [Click here.](${src.url})`)
                 message.channel.send({ embed: embed })
                  }).catch(e => {
                    message.channel.send(`Error: ${e}`)
              });
};
      var embed3 = new Discord.MessageEmbed()
      .setTitle("ERROR:")
      .setColor("#ffb6c1")
      .addField("Evaled: :inbox_tray:", `\`\`\`js\n${code}\n\`\`\``)
      .addField("Output: :outbox_tray:", `\`ERROR\` \`\`\`js\n${clean(err)}\n\`\`\``)
      message.channel.send({embed: embed3 });
    }
  }

**Comment by jeydinpham** [comment]
It does?

**Comment by DragonZV** [comment]
> It does?

Yeah.

**Pull request merged**
