### PR TITLE
Added 6 commands

### PR DESCRIPTION
**Pull request by achaljhawar**
1 . cringerate
2 . advice
3 . catfact
4.  kill
5. pp
6. dankrate

### CODE REVIEW

**Comment by DragonZV** [comment]
image

**Comment by DragonZV** [comment]
image
.catch is for catching an error with a promise.

**Comment by DragonZV** [comment]
Also, we have a function for getting a user. `await client.functions.getMember(true, message, args[0]);`

**Comment by achaljhawar** [comment]
> image
> .catch is for catching an error with a promise.

fixed

**Pull request merged**
